### ISSUE TITLE
While updating an existing key, the TTL value is lost

### ISSUE THREAD

**Issue by kaushikmahato** [AkashBabu/redis-json#11] opened 2020-08-14 17:01 UTC
When using redis-json (v^3.2.0), we have observed few keys get a new entry in redis with appended `_t` without any TTL.
From my understanding it occurs when we are updating an existing key, I believe its by design.

But the problem is it doesn't copies the TTL value of the the original key, and the original key's TTL is also lost.

How to prevent this from happening ?

**Comment by AkashBabu** [comment] 2020-08-15 03:27
@kaushikmahato , `_t` signifies the type information of the corresponding data stored in redis. But please note that this was released in `v4.0.0`. Please check [release notes](anticlockwise). Also this issue was addressed during the initial release of type support for data in `v4.0.0`. Please check this [line of code](https://github.com/AkashBabu/redis-json/blob/8475687ec23034cebd4da3f9693c7882088441ca/src/lib/jsonCache.ts#L99).

So if you could re-check the version and provide a reproducible code, it would really help me to debug the issue quicker.

**Comment by AkashBabu** [comment] 2020-08-20 04:34
Hi @kaushikmahato , can you please close the issue if I've answered your question, else reply

**Comment by AkashBabu** [comment] 2020-08-25 10:27
Since there is no response, I'll go ahead and close this ticket. Please feel free to reopen the ticket, if need be.

**Closed as completed by AkashBabu** 2020-08-25 10:27 UTC
